version: '3.4'

services:
  health-check:
    image: health-check
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - 5432:5432
    volumes:
      - ./.sql/init-health-check-db.sql:/docker-entrypoint-initdb.d/init.sql
