version: '3.4'

services:
  health-check:
    image: health-check
    env_file:
      - .env
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - $PORT:$PORT
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./.sql/init-health-check-db.sql:/docker-entrypoint-initdb.d/init.sql
